easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Proposition
       - App\Entity\Question
       - App\Entity\Questionnaire
       - App\Entity\Reponse
       - App\Entity\User
